Hw 2 tests
GenesisEducationKyiv/main-project-IrynaBohatchenko pull request #3
Opened 2023-06-24 20:11 UTC by IrynaBohatchenko

2023-06-26 17:43 UTC, vadimpk requested changes

2023-06-26 17:43 UTC, vadimpk commented on internal/emailstorage/storage_test.go
> +	}
```suggestion
	}
	
```

2023-06-26 17:43 UTC, vadimpk commented on internal/emailstorage/storage_test.go
> +	}
```suggestion
	}
	
```

2023-06-26 17:43 UTC, vadimpk commented on internal/emailstorage/storage_test.go
> +func TestStorage_validateEmail(t *testing.T) {
It's considered a good practice to run tests in parallel, so consider using t.Parallel() at the begging of this function

2023-06-26 17:43 UTC, vadimpk commented on internal/emailstorage/storage_test.go
> +			fields: fields{path: "./emails_test.txt"},
The function you are testing doesn't really require a path to the storage, so you can remove this `fields` argument and init your `Storage` without it

2023-06-26 17:43 UTC, vadimpk commented on internal/btcpriceservice/service_test.go
> +// integration test of file storage
Consider adding a build tag to separate your integration tests from unit tests: [link](https://mickey.dev/posts/go-build-tags-testing/)
It could be beneficial in the future, if you want to separate those types of tests

2023-06-26 17:43 UTC, vadimpk commented on internal/btcpriceservice/service_test.go
> +		file, err := os.Create(filePath)
Your `Storage.AddEmail()` should create the file, so I don't think it is necessary to do that here. You can just leave `defer`. But I would recommend using `suite` to tear down test files after tests are completed, it is a more clear approach I think

2023-06-26 17:43 UTC, vadimpk commented on internal/btcpriceservice/service_test.go
> +func TestService_HandleSubscribe(t *testing.T) {
Have you considered using table tests for this test?

2023-06-26 17:43 UTC, vadimpk commented on cmd/price_check/handler_test.go
> +	tempSrv := httptest.NewServer(makeTestRouter(cfg))
Consider using `httptest.NewRecorder()` here

2023-06-26 17:43 UTC, vadimpk commented on cmd/price_check/handler_test.go
> +			t.Fatalf("Expected no error, got %v", err)
You can use `assert` here instead, so that other tests will run even if this one fails

2023-06-26 17:43 UTC, vadimpk commented on cmd/price_check/handler_test.go
> +	}
Consider using `suite`, it will help you with cleaning your tests, and also storing some shared data between different tests

2023-06-26 17:43 UTC, vadimpk commented on cmd/price_check/handler_test.go
> +		logger)
```suggestion
		logger
	)
```

2023-06-26 19:01 UTC, fabl3ss commented on cmd/price_check/handler_test.go
> +	logger, _ := zap.NewProduction()
```suggestion
	logger, _ := zap.NewDevelopment()
```

Зараз в проєкті немає логів рівня DebugLevel, але краще відразу закласти це, ніж потім бігати і міняти

2023-06-26 19:07 UTC, fabl3ss commented on cmd/price_check/handler_test.go
> +func Test_handle_rate(t *testing.T) {
Рекомендую притримуватись гошних конвеншнів по неймінгу
https://go.dev/doc/effective_go#mixed-caps

2023-06-26 19:47 UTC, fabl3ss commented on cmd/price_check/handler_test.go
> +		t.Parallel()
```suggestion
```

В паралель краще не запускати тести які не повністю ізольовані (в цьому випадку взаємодіють з файловою системою).

Локально запустивши тести отримував наступну помилку:
```
--- FAIL: Test_handle_subscribe (0.00s)
    --- FAIL: Test_handle_subscribe/check_subscribing (0.00s)
        handler_test.go:115: 
                Error Trace:    /Users/maksym.chaika/main-project-IrynaBohatchenko/cmd/price_check/handler_test.go:115
                Error:          Not equal: 
                                expected: 200
                                actual  : 409
                Test:           Test_handle_subscribe/check_subscribing
```

2023-06-26 20:04 UTC, fabl3ss commented on internal/btcpriceservice/service_test.go
> +			assert.True(t, strings.Contains(scanner.Text(), email))
Цю перевірку краще переробити, у випадку якщо щось піде не так і email збережеться як test_test_email@gmail.com, тест цього не покриє

2023-06-26 20:25 UTC, fabl3ss commented on cmd/price_check/handler_test.go
> +		t.Parallel()
```suggestion
```

В паралель краще не запускати тести, які повністю не ізольовані (в цьому випадку взаємодіють з файловою системою).

Локально запустивши тести отримував наступну помилку:
```
--- FAIL: Test_handle_subscribe (0.00s)
    --- FAIL: Test_handle_subscribe/check_subscribing (0.00s)
        handler_test.go:115: 
                Error Trace:    /Users/maksym.chaika/main-project-IrynaBohatchenko/cmd/price_check/handler_test.go:115
                Error:          Not equal: 
                                expected: 200
                                actual  : 409
                Test:           Test_handle_subscribe/check_subscribing
```

2023-06-26 20:26 UTC, fabl3ss commented
Рекомендую дописати декілька сценаріїв, які перевіряють що повернеться очікувана помилка.
Вже була пропозиція від @vadimpk додати тест сьюти, підтримую цю ідею, це дозволить зробити тести більш читабельними і прибере дублювання.

Стосовно PR'ів з домашкою, краще для base branch обирати гілку з попереднім ДЗ, і коли воно буде змержено, міняти base branch на main. Це потрібно для того, щоб було очевидніше які зміни було внесено.

2023-06-27 15:29 UTC, IrynaBohatchenko commented on internal/btcpriceservice/service_test.go
> +		file, err := os.Create(filePath)
`Storage.AddEmail()` only opens file with `os.OpenFile` which doesn't create file in my case as I didn't pass the O_CREATE flag.

2023-06-27 16:57 UTC, IrynaBohatchenko commented on internal/btcpriceservice/service_test.go
> +func TestService_HandleSubscribe(t *testing.T) {
No, because test process is a bit different in two cases. However, I'll check, if using of Suite will help with it.

2023-07-01 19:57 UTC, merged